import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ToastProvider from "@/context/toastContext";
import { ProductProvider } from "@/context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lizit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <ProductProvider>
            {children}
          </ProductProvider>
        </ToastProvider>
      </body>

    </html>
  );
}
